[build]
  publish = "public"

[[redirects]]
  from = "/impressum"
  to = "/impressum.html"
  status = 200

[[redirects]]
  from = "/datenschutz"
  to = "/datenschutz.html"
  status = 200

[[redirects]]
  from = "/generator"
  to = "/generator.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
